@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package io.github.ocelot.refinedchemistry.common.registry;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;