@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package io.github.ocelot.refinedchemistry.datagen;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;